name: CI/CD - Gnostex Backend API

on:
#  push:
#    branches: [ "main" ]

  push:
    branches: [ "main", "develop" ]
#  pull_request:
#    branches: [ "main", "develop" ]

jobs:
  #build-test-docker:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # Tests (quality gate)
      - name: Run tests unit & integration tests
        run: mvn clean verify

      # verify GHCR access
      - name: Debug secrets
        run: |
          echo "Username length: ${#GHCR_USERNAME}"
          echo "Token length: ${#GHCR_TOKEN}"
        env:
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}


      # Login to GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Build & push image
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          push: true
#          tags: |
#            ghcr.io/${{ secrets.GHCR_USERNAME }}/gnostex-backend-api:latest
#            ghcr.io/${{ secrets.GHCR_USERNAME }}/gnostex-backend-api:${{ github.sha }}

      # Deploy to VPS
      # GHCR github container repository -- container images


#      - name: Deploy to VPS
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.VPS_HOST }}
#          username: ${{ secrets.VPS_USER }}
#          key: ${{ secrets.VPS_SSH_KEY }}
#          script: |
#            docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_TOKEN }}
#
#            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/gnostex-backend-api:latest
#
#            docker stop gnostex-backend-api || true
#            docker rm gnostex-backend-api || true
#
#            docker run -d \
#              --name gnostex-backend-api \
#              --restart unless-stopped \
#              -p 8080:8080 \
#              -e SPRING_PROFILES_ACTIVE=dev \
#              -e DB_URL=jdbc:postgresql://host.docker.internal:5432/gnostexdb \
#              -e DB_USERNAME=gnostex \
#              -e DB_PASSWORD=gnostex \
#              ghcr.io/${{ secrets.GHCR_USERNAME }}/gnostex-backend-api:latest





#name: ci

#on:
#  push:
#    branches: [ "*" ]
#  pull_request:

#jobs:
#  build:
#    runs-on: ubuntu-latest

#    steps:
#      - uses: actions/checkout@v4

#      - name: Set up JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: 21

#      - name: Build
#        run: ./mvnw clean test